version: '3.6'

services:

  front:
    depends_on:
      - back
    build:
      context: ./front
    volumes:
      - './front:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3000'
    command: sh -c "sleep 5; yarn start"
    environment:
      - CLIENT_ID=MUtc7j__DEwLlbxjG4xc7TLliT2m1wId
      - DOMAIN=dev-test1.auth0.com

  back:
#    container_name: back
    depends_on:
      - mongo
    build:
      context: ./back
#      context: .
#      dockerfile: Dockerfile_back
    volumes:
      - './back:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
#    command: sh -c "yarn start"
#    command: sh -c "sleep 5; node ."
    command: sh -c "sleep 5; yarn start"
    environment:
      - COMPOSE_HTTP_TIMEOUT=200

  mongo:
    image: mongo
#    container_name: mongodb
    ports:
    - "27016:27017"
    volumes:
    - data-volume:/data/db

volumes:
  data-volume:
